Update Makefile

diff --git a/backends/ara/Makefile b/backends/ara/Makefile
--- a/backends/ara/Makefile
+++ b/backends/ara/Makefile
@@ -26,29 +26,29 @@ apply-patches:
 	cd $(ARA_DIR)/hardware && make apply-patches
 
 app:
-        @if [ -z "$(KERNEL)" ]; then \
-                echo "[ARA][ERROR] Please specify a kernel, e.g. make app KERNEL=fmatmul_8"; \
-                exit 1; \
-        fi
-        @echo "[ARA] Building kernel $(KERNEL)..."
-        @cd $(ARA_DIR)/apps && \
-        if [ ! -L "$(KERNEL)" ]; then \
-                echo "[ARA] Linking $(KERNEL) -> ../../../../kernel/$(KERNEL)"; \
-                ln -sfn ../../../../kernel/$(KERNEL) $(KERNEL); \
-        fi && \
-        if [ -d "$(abspath $(SELF_DIR)/../../data)/$(KERNEL)" ]; then \
-                echo "[ARA] Copying dataset sources for $(KERNEL)"; \
-                cp -u $(abspath $(SELF_DIR)/../../data)/$(KERNEL)/*.c $(KERNEL)/ || true; \
-        fi && \
-        make bin/$(KERNEL) \
-             APPS_DIR=$(abspath $(SELF_DIR)/../../kernel) \
-             ENV_DEFINES="-I$(COMMON_DIR) -I$(DATA_DIR) -I$(DATA_DIR)/$(KERNEL) -I$(abspath $(SELF_DIR)/../../kernel)/$(KERNEL)/inc"
+	@if [ -z "$(KERNEL)" ]; then \
+    	echo "[ARA][ERROR] Please specify a kernel, e.g. make app KERNEL=fmatmul_8"; \
+        exit 1; \
+    fi
+    @echo "[ARA] Building kernel $(KERNEL)..."
+    @cd $(ARA_DIR)/apps && \
+    if [ ! -L "$(KERNEL)" ]; then \
+        echo "[ARA] Linking $(KERNEL) -> ../../../../kernel/$(KERNEL)"; \
+        ln -sfn ../../../../kernel/$(KERNEL) $(KERNEL); \
+    fi && \
+    if [ -d "$(abspath $(SELF_DIR)/../../data)/$(KERNEL)" ]; then \
+        echo "[ARA] Copying dataset sources for $(KERNEL)"; \
+        cp -u $(abspath $(SELF_DIR)/../../data)/$(KERNEL)/*.c $(KERNEL)/ || true; \
+    fi && \
+    make bin/$(KERNEL) \
+    	APPS_DIR=$(abspath $(SELF_DIR)/../../kernel) \
+    	ENV_DEFINES="-I$(COMMON_DIR) -I$(DATA_DIR) -I$(DATA_DIR)/$(KERNEL) -I$(abspath $(SELF_DIR)/../../kernel)/$(KERNEL)/inc"
 
 
 run:
-        @if [ -z "$(KERNEL)" ]; then \
-                echo "[ARA][ERROR] Please specify a kernel, e.g. make run KERNEL=fmatmul_32"; \
-                exit 1; \
-        fi
-        @echo "[ARA] Running kernel $(KERNEL) with Verilator..."
-        cd $(ARA_DIR)/hardware && app=$(KERNEL) make simv
+    @if [ -z "$(KERNEL)" ]; then \
+        echo "[ARA][ERROR] Please specify a kernel, e.g. make run KERNEL=fmatmul_32"; \
+        exit 1; \
+    fi
+    	@echo "[ARA] Running kernel $(KERNEL) with Verilator..."
+    	cd $(ARA_DIR)/hardware && app=$(KERNEL) make simv
